import js from '@eslint/js';
import ts from 'typescript-eslint';
import svelte from 'eslint-plugin-svelte';
import globals from 'globals';
import svelteConfig from './svelte.config.js';

/**
 * Flat config. Three layers:
 *   1. baseline correctness (eslint:recommended + typescript-eslint type-aware)
 *   2. Svelte 5 idiom (eslint-plugin-svelte, parsed with the real svelte.config.js)
 *   3. this repo's own conventions
 *
 * Severity policy: `error` is reserved for findings that are actionable now and
 * few enough to fix. The type-safety debt inherited from the pre-lint era
 * (the `no-unsafe-*` family, ~195 findings) is `warn` so CI can gate on errors
 * immediately instead of waiting for a mass cleanup. Run `bunx eslint .` to see
 * the backlog; it is meant to shrink, not to stay.
 */
export default [
  {
    ignores: [
      'dist/',
      'node_modules/',
      'test-results/',
      'playwright-report/',
      '.playwright-mcp/',
      'public/',
      // Generated by scripts/, not authored.
      'src/utils/iconPaths.ts',
      'src/constants/degreeBucketRules.ts',
      // tsconfig excludes these, so the type-aware parser cannot see them.
      'tests/e2e/_*.spec.ts',
    ],
  },

  js.configs.recommended,
  ...ts.configs.recommendedTypeChecked,
  ...svelte.configs.recommended,

  {
    languageOptions: {
      globals: { ...globals.browser },
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
        extraFileExtensions: ['.svelte'],
      },
    },
  },

  {
    files: ['**/*.svelte', '**/*.svelte.ts'],
    languageOptions: {
      parserOptions: { parser: ts.parser, svelteConfig },
    },
  },

  // Workers have no `window`; scripts/ runs under Bun, not the browser.
  {
    files: ['src/workers/**/*.ts'],
    languageOptions: { globals: { ...globals.worker } },
  },
  {
    files: ['scripts/**/*.ts', '*.config.ts', '*.config.js'],
    languageOptions: { globals: { ...globals.node } },
  },

  {
    rules: {
      // tsconfig already runs noUnusedLocals/noUnusedParameters, and
      // svelte-check reports the same finding a third time.
      '@typescript-eslint/no-unused-vars': 'off',

      // --- errors: actionable, low volume -------------------------------
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      '@typescript-eslint/await-thenable': 'error',
      '@typescript-eslint/prefer-promise-reject-errors': 'error',
      'no-async-promise-executor': 'error',
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-var': 'error',

      // --- warnings: inherited debt, visible but non-blocking -----------
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unsafe-assignment': 'warn',
      '@typescript-eslint/no-unsafe-member-access': 'warn',
      '@typescript-eslint/no-unsafe-argument': 'warn',
      '@typescript-eslint/no-unsafe-call': 'warn',
      '@typescript-eslint/no-unsafe-return': 'warn',
      '@typescript-eslint/no-unsafe-enum-comparison': 'warn',
      '@typescript-eslint/restrict-template-expressions': 'warn',
      '@typescript-eslint/require-await': 'warn',
      '@typescript-eslint/no-unnecessary-type-assertion': 'warn',
      '@typescript-eslint/no-redundant-type-constituents': 'warn',
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      'no-useless-assignment': 'warn',
      'preserve-caught-error': 'warn',

      // Off after reading all 10 findings: every one was a false positive.
      // They were $derived.by() locals that never escape their closure,
      // copy-on-write state (`const next = new Set(prev); ...; state = next`,
      // which is the correct Svelte 5 idiom -- SvelteSet would make it
      // mutation-based and change behavior), module-level bookkeeping maps, and
      // two `new Date()` passed straight into toLocaleDateString.
      // The distinction is already being drawn correctly by hand: see
      // termExpansion.svelte.ts:20, which uses SvelteMap for the one collection
      // in that file that really is read reactively.
      'svelte/prefer-svelte-reactivity': 'off',

      // termsByCourse in AutoScheduleIntro.svelte is reassigned, so dropping
      // the $state() wrapper around its SvelteMap would break reactivity.
      'svelte/no-unnecessary-state-wrap': ['error', { allowReassign: true }],

      // Every {@html} in this repo is either getInlineSVG() over the generated
      // icon path table or an authored tutorial step description -- no user
      // input reaches either. 57 findings, all deliberate.
      'svelte/no-at-html-tags': 'off',

      // `let { x } = $props()` cannot be const: the compiler reassigns props.
      // svelte/prefer-const knows that; the core rule does not.
      'prefer-const': 'off',
      'svelte/prefer-const': [
        'error',
        { excludedRunes: ['$props', '$derived'] },
      ],

      'no-restricted-syntax': [
        'error',
        {
          selector:
            'AssignmentExpression > MemberExpression.left[property.name=/^(transition|animation|transitionDuration|animationDuration)$/][object.property.name="style"]',
          message:
            'Do not tween via inline style.transition/animation. Use a Svelte transition: directive, or element.animate() inside an action.',
        },
        {
          selector:
            'AssignmentExpression > MemberExpression.left[property.name="onfinish"]',
          message:
            'Do not chain animations with .onfinish. Sequence with the animation.finished promise, or the WAAPI `delay` option.',
        },
      ],
    },
  },

  {
    files: ['**/*.svelte', '**/*.svelte.ts'],
    rules: {
      // A bare `someState;` inside $effect is the idiomatic way to register a
      // dependency without using the value. The base rule reads it as dead code.
      '@typescript-eslint/no-unused-expressions': 'off',

      // The no-unsafe-* family cannot work through svelte-eslint-parser. Types
      // are lost crossing the compiler's intermediate representation, so fully
      // typed source still reads as `any`: Modal.svelte declares
      // `children: Snippet<[() => void]>` yet `{#snippet children(close)}`
      // yields `close: any`, and TextField.svelte declares
      // `onchange?: (event: Event) => void` yet inline arrows at call sites get
      // `e: any`. tsc and svelte-check accept every one of these. There is
      // nothing to annotate -- the only fix would be ~18 inline disables that
      // catch no real defects.
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
    },
  },

  // Tests assert on shapes TypeScript cannot always see, and Playwright specs
  // legitimately log.
  {
    files: ['tests/**/*.ts', 'src/**/*.test.ts', 'src/**/*.svelte.test.ts'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      'no-console': 'off',
    },
  },

  // Scripts are CLI tools; printing IS their output.
  {
    files: ['scripts/**/*'],
    rules: { 'no-console': 'off' },
  },

  // One-off data-munging CLI tools. They parse external JSON and scraped
  // GraphQL, `any` is the honest type for that, and nothing under src/ imports
  // them -- their only output is public/*.json, which the app fetches at
  // runtime. Same argument the tests/ block above already makes.
  //
  // scripts/**/types.ts is deliberately excluded: rateMyProfessor/types.ts is
  // not a munging script but the schema for public/rateMyProfessor.json, whose
  // consumer (RateMyProfessorService.ts) is a genuine unsafe boundary. Relaxing
  // it would disarm the producer side of a live contract.
  {
    files: ['scripts/**/*.ts', 'scripts/**/*.mjs'],
    ignores: ['scripts/**/types.ts'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/restrict-template-expressions': 'off',
    },
  },

  // logger.ts IS the logging abstraction -- it wraps console.* behind an
  // import.meta.env.DEV guard. It is the one correct place for a raw console.
  {
    files: ['src/utils/logger.ts'],
    rules: { 'no-console': 'off' },
  },

  // Plain-JS files are not in the TS program (tsconfig has no allowJs), so
  // type-aware rules cannot run on them. Must come last -- later blocks win,
  // and the rules block above would otherwise switch them back on.
  {
    files: ['**/*.js', '**/*.mjs', '**/*.cjs'],
    ...ts.configs.disableTypeChecked,
  },
];
