import js from '@eslint/js';
import ts from 'typescript-eslint';
import svelte from 'eslint-plugin-svelte';
import globals from 'globals';
import svelteConfig from './svelte.config.js';

/**
 * Flat config: eslint:recommended + typescript-eslint (type-aware) +
 * eslint-plugin-svelte, then this repo's own rules.
 *
 * Severity policy: `error` for anything worth blocking CI on; `warn` for the
 * large `no-unsafe-*` backlog, which is meant to shrink over time.
 */
export default [
  {
    ignores: [
      'dist/',
      'node_modules/',
      'test-results/',
      'playwright-report/',
      '.playwright-mcp/',
      'public/',
      // Generated by scripts/, not authored.
      'src/utils/iconPaths.ts',
      'src/constants/degreeBucketRules.ts',
      // tsconfig excludes these, so the type-aware parser cannot see them.
      'tests/e2e/_*.spec.ts',
    ],
  },

  js.configs.recommended,
  ...ts.configs.recommendedTypeChecked,
  ...svelte.configs.recommended,

  {
    languageOptions: {
      globals: { ...globals.browser },
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
        extraFileExtensions: ['.svelte'],
      },
    },
  },

  {
    files: ['**/*.svelte', '**/*.svelte.ts'],
    languageOptions: {
      parserOptions: { parser: ts.parser, svelteConfig },
    },
  },

  // Workers have no `window`; scripts/ runs under Bun, not the browser.
  {
    files: ['src/workers/**/*.ts'],
    languageOptions: { globals: { ...globals.worker } },
  },
  {
    files: ['scripts/**/*.ts', '*.config.ts', '*.config.js'],
    languageOptions: { globals: { ...globals.node } },
  },

  {
    rules: {
      // Already reported by tsconfig's noUnusedLocals and by svelte-check.
      '@typescript-eslint/no-unused-vars': 'off',

      // --- errors: actionable, low volume -------------------------------
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      '@typescript-eslint/await-thenable': 'error',
      '@typescript-eslint/prefer-promise-reject-errors': 'error',
      'no-async-promise-executor': 'error',
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-var': 'error',

      // --- warnings: inherited debt, visible but non-blocking -----------
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unsafe-assignment': 'warn',
      '@typescript-eslint/no-unsafe-member-access': 'warn',
      '@typescript-eslint/no-unsafe-argument': 'warn',
      '@typescript-eslint/no-unsafe-call': 'warn',
      '@typescript-eslint/no-unsafe-return': 'warn',
      '@typescript-eslint/no-unsafe-enum-comparison': 'warn',
      '@typescript-eslint/restrict-template-expressions': 'warn',
      '@typescript-eslint/require-await': 'warn',
      '@typescript-eslint/no-unnecessary-type-assertion': 'warn',
      '@typescript-eslint/no-redundant-type-constituents': 'warn',
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      'no-useless-assignment': 'warn',
      'preserve-caught-error': 'warn',

      // The flagged collections are never read reactively; the ones that are
      // already use SvelteMap.
      'svelte/prefer-svelte-reactivity': 'off',

      // termsByCourse in AutoScheduleIntro.svelte is reassigned, so it needs
      // the $state() wrapper around its SvelteMap.
      'svelte/no-unnecessary-state-wrap': ['error', { allowReassign: true }],

      // Every {@html} here renders a generated icon path or authored tutorial
      // text -- no user input reaches one.
      'svelte/no-at-html-tags': 'off',

      // `let { x } = $props()` cannot be const -- the compiler reassigns
      // props. Only the svelte version of the rule knows that.
      'prefer-const': 'off',
      'svelte/prefer-const': [
        'error',
        { excludedRunes: ['$props', '$derived'] },
      ],

      'no-restricted-syntax': [
        'error',
        {
          selector:
            'AssignmentExpression > MemberExpression.left[property.name=/^(transition|animation|transitionDuration|animationDuration)$/][object.property.name="style"]',
          message:
            'Do not tween via inline style.transition/animation. Use a Svelte transition: directive, or element.animate() inside an action.',
        },
        {
          selector:
            'AssignmentExpression > MemberExpression.left[property.name="onfinish"]',
          message:
            'Do not chain animations with .onfinish. Sequence with the animation.finished promise, or the WAAPI `delay` option.',
        },
      ],
    },
  },

  {
    files: ['**/*.svelte', '**/*.svelte.ts'],
    rules: {
      // A bare `someState;` in $effect registers a dependency, not dead code.
      '@typescript-eslint/no-unused-expressions': 'off',

      // svelte-eslint-parser loses types, so snippet params and callback props
      // read as `any` however they are declared. tsc and svelte-check do see
      // them, so there is nothing to fix.
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
    },
  },

  // Tests assert on shapes TypeScript cannot see, and specs legitimately log.
  {
    files: ['tests/**/*.ts', 'src/**/*.test.ts', 'src/**/*.svelte.test.ts'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      'no-console': 'off',
    },
  },

  // Scripts are CLI tools; printing IS their output.
  {
    files: ['scripts/**/*'],
    rules: { 'no-console': 'off' },
  },

  // One-off CLI tools parsing external JSON and scraped GraphQL; same argument
  // as the tests/ block. types.ts is excluded -- the app reads what it types.
  {
    files: ['scripts/**/*.ts', 'scripts/**/*.mjs'],
    ignores: ['scripts/**/types.ts'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/restrict-template-expressions': 'off',
    },
  },

  // The logging abstraction itself: the one correct place for a raw console.
  {
    files: ['src/utils/logger.ts'],
    rules: { 'no-console': 'off' },
  },

  // Plain-JS files are not in the TS program (no allowJs), so type-aware rules
  // cannot run on them. Must come last: later blocks win.
  {
    files: ['**/*.js', '**/*.mjs', '**/*.cjs'],
    ...ts.configs.disableTypeChecked,
  },
];
