import type { KnipConfig } from 'knip';
import { compile } from 'svelte/compiler';

/**
 * Finds cross-file dead code: unused files, unused exports, unused types, and
 * unused dependencies. This is the gap tsconfig's noUnusedLocals cannot see --
 * it catches unused *locals*, never an export nobody imports.
 *
 * The svelte compiler override is required, not optional: Knip's built-in
 * .svelte handling is a regex extractor that only finds import statements, so
 * exports declared in components get reported as unused. Running the real
 * compiler makes them visible.
 */
export default {
  entry: [
    // index.html already pulls in src/main.ts, so main is not listed here.
    //
    // There is no --production script: that mode does not resolve this HTML
    // entry, so it walks an empty graph and calls every dependency unused.
    'index.html',
    // Workers are instantiated by URL, not imported, so nothing in the module
    // graph points at them.
    'src/workers/*.worker.ts',
    // Standalone CLI tools invoked via package.json scripts or by hand.
    'scripts/**/*.{ts,mjs}',
    'tests/**/*.{test,spec}.ts',
    '*.config.{ts,js}',
  ],
  project: ['src/**/*.{ts,svelte}', 'scripts/**/*.{ts,mjs}', 'tests/**/*.ts'],
  ignore: [
    // Generated by scripts/generate-icon-paths.ts, not authored.
    'src/utils/iconPaths.ts',
  ],
  compilers: {
    svelte: (source: string) => compile(source, {}).js.code,
  },
} satisfies KnipConfig;
