import type { KnipConfig } from 'knip';
import { compile } from 'svelte/compiler';

/**
 * The Svelte compiler erases type-only imports, so Knip never sees a component
 * use a type and calls it an unused export. Recover them from the source and
 * re-emit them alongside the compiled output.
 */
const IMPORT_RE = /\bimport\s+([\s\S]*?)\s+from\s*['"]([^'"]+)['"]/g;

const typeImportsOf = (source: string): string[] => {
  const statements: string[] = [];

  for (const [, clause, specifier] of source.matchAll(IMPORT_RE)) {
    // `import type { A, B } from '...'` / `import type A from '...'`
    if (/^type\b/.test(clause)) {
      statements.push(`import ${clause} from '${specifier}';`);
      continue;
    }

    // `import { value, type A }` -- the value half survived compilation, so
    // re-emit only the `type` specifiers.
    const named = clause.match(/\{([\s\S]*)\}/);
    if (!named) continue;

    const types = named[1]
      .split(',')
      .map(entry => entry.trim())
      .filter(entry => /^type\s/.test(entry))
      .map(entry => entry.replace(/^type\s+/, ''));

    if (types.length > 0) {
      statements.push(
        `import type { ${types.join(', ')} } from '${specifier}';`,
      );
    }
  }

  return statements;
};

const svelteCompiler = (source: string): string =>
  [compile(source, {}).js.code, ...typeImportsOf(source)].join('\n');

/**
 * Finds cross-file dead code -- unused files, exports, types, and dependencies
 * -- which tsconfig's noUnusedLocals cannot see.
 *
 * The svelte compiler override is required: Knip's built-in .svelte handling
 * only extracts imports, so every component export would read as unused.
 */
export default {
  entry: [
    // index.html pulls in src/main.ts, so main is not listed separately.
    // Do not run knip --production: that mode skips HTML entries, walks an
    // empty graph, and calls every dependency unused.
    'index.html',
    // Instantiated by URL, so nothing in the module graph points at them.
    'src/workers/*.worker.ts',
    // Standalone CLI tools invoked via package.json scripts or by hand.
    'scripts/**/*.{ts,mjs}',
    'tests/**/*.{test,spec}.ts',
    '*.config.{ts,js}',
  ],
  project: ['src/**/*.{ts,svelte}', 'scripts/**/*.{ts,mjs}', 'tests/**/*.ts'],
  ignore: [
    // Generated by scripts/generate-icon-paths.ts, not authored.
    'src/utils/iconPaths.ts',
  ],
  compilers: {
    svelte: svelteCompiler,
  },
} satisfies KnipConfig;
