// AUTO-GENERATED by scripts/generateDegreeBucketRules.mjs — do not edit by hand.
// Source: WPI program tracking sheets (all degrees, classes 2026-2030).
// For each degree-requirement bucket: which DEPARTMENTS may fill it, plus specific
// course-code EXCLUSIONS that do not count even though their department qualifies.
//
// Layered model: WPI_WIDE_RULES holds institution-wide buckets (written once);
// MAJOR_RULES holds per-major deviations + major-specific buckets, keyed by class
// (graduation) year, emitting a year entry only when the ruleset changes. The
// resolver in src/services/degree/degreeBucketRules.ts merges them (major wins) and
// picks the newest year <= the student's.

import type { RequirementCategory } from '../types/degree';

export interface DegreeBucketRule {
    /** Same union the degree-import classifier uses. */
    category: RequirementCategory;
    /** Sheet section header; disambiguates multiple major_specific buckets. */
    label: string;
    /** UPPERCASE valid department codes. Empty => no department restriction. */
    validDepartments: string[];
    /** Course codes excluded despite a valid department ("DEPT NUMBER"). */
    excludedCourses: string[];
}

export type SheetRules = DegreeBucketRule[];
/** classYear -> rules (sparse: only years whose ruleset differs from the prior year). */
export type DegreeYearRules = Record<number, SheetRules>;
/** majorKey -> classYear -> rules. majorKey matches StudentRecord.major. */
export type DegreeBucketRuleSet = Record<string, DegreeYearRules>;

/** Institution-wide buckets shared by every degree (overridable per major). */
export const WPI_WIDE_RULES: SheetRules = [
    { category: 'social_science', label: "Social Science", validDepartments: ["DEV","ECON","ENV","GOV","ID","PSY","SD","SOC","SS","STS"], excludedCourses: [] },
    { category: 'hua', label: "Humanities & Arts", validDepartments: ["AB","AR","EN","GN","HI","HU","ID","INTL","MU","PY","RE","SP","TH"], excludedCourses: [] },
    { category: 'physical_education', label: "Physical Education", validDepartments: ["WPE"], excludedCourses: [] },
    { category: 'free_electives', label: "Free Electives", validDepartments: [], excludedCourses: [] },
];

export const MAJOR_RULES: DegreeBucketRuleSet = {
    "Actuarial Mathematics": {
        2026: [
            { category: 'major_specific', label: "BASIC SCIENCE (2/3 units)", validDepartments: ["BB","CH","ES","GE","PH"], excludedCourses: [] },
            { category: 'major_specific', label: "BUSINESS (4/3 unit)", validDepartments: ["ACC","BUS","FIN"], excludedCourses: ["FIN 1250"] },
            { category: 'major_specific', label: "COMPUTER SCIENCE OR DATA SCIENCE (2/3 unit)", validDepartments: ["CS","DS"], excludedCourses: [] },
            { category: 'major_specific', label: "MATHEMATICS (22/3 units)", validDepartments: ["MA"], excludedCourses: [] },
        ],
        2027: [
            { category: 'major_specific', label: "BASIC SCIENCE (2/3 units)", validDepartments: ["BB","CH","ES","GE","PH"], excludedCourses: [] },
            { category: 'major_specific', label: "BUSINESS (4/3 units)", validDepartments: ["ACC","BUS","FIN"], excludedCourses: ["FIN 1250"] },
            { category: 'major_specific', label: "COMPUTER SCIENCE OR DATA SCIENCE (2/3 units)", validDepartments: ["CS","DS"], excludedCourses: [] },
            { category: 'major_specific', label: "MATHEMATICS (22/3 units)", validDepartments: ["MA"], excludedCourses: [] },
            { category: 'social_science', label: "SOCIAL SCIENCE (2/3 units)", validDepartments: ["ECON","ENV","GOV","ID","PSY","SD","SOC","SS","STS"], excludedCourses: [] },
        ],
    },
    "Aerospace Engineering-Aeronautical": {
        2026: [
            { category: 'major_specific', label: "CHEMISTRY (1/3 unit) Course with prefix: CH", validDepartments: ["CH"], excludedCourses: [] },
            { category: 'major_specific', label: "MATHEMATICS (6/3 unit) Courses with prefix: MA", validDepartments: ["MA"], excludedCourses: [] },
            { category: 'major_specific', label: "PHYSICS (2/3 unit) Courses with prefix: PH", validDepartments: ["PH"], excludedCourses: [] },
        ],
    },
    "Aerospace Engineering-Astronautical": {
        2026: [
            { category: 'major_specific', label: "CHEMISTRY (1/3 unit) Course with prefix: CH", validDepartments: ["CH"], excludedCourses: [] },
            { category: 'major_specific', label: "MATHEMATICS (6/3 unit) Courses with prefix: MA", validDepartments: ["MA"], excludedCourses: [] },
            { category: 'major_specific', label: "PHYSICS (2/3 unit) Courses with prefix: PH", validDepartments: ["PH"], excludedCourses: [] },
        ],
    },
    "Architectural Engineering": {
        2026: [
            { category: 'major_specific', label: "CHEMISTRY (1/3 unit) Course with prefix: CH", validDepartments: ["CH"], excludedCourses: [] },
            { category: 'major_specific', label: "MATHEMATICS (7/3 unit) Courses with prefix: MA", validDepartments: ["MA"], excludedCourses: [] },
            { category: 'major_specific', label: "PHYSICS (2/3 unit) Courses with prefix: PH", validDepartments: ["PH"], excludedCourses: [] },
        ],
    },
    "Artificial Intelligence": {
        2030: [
            { category: 'major_specific', label: "COMPUTER SCIENCE", validDepartments: ["CS"], excludedCourses: [] },
            { category: 'major_specific', label: "MATHEMATICAL SCIENCES", validDepartments: ["MA"], excludedCourses: [] },
            { category: 'major_specific', label: "NATURAL & ENGINEERING SCIENCE", validDepartments: ["AE","AREN","BB","BCB","BME","CE","CH","CHE","ECE","ES","GE","ME","NEU","PH","RBE"], excludedCourses: [] },
            { category: 'social_science', label: "SOCIAL SCIENCE", validDepartments: ["ECON","ENV","GOV","ID","PSY","SD","SOC","SS","STS"], excludedCourses: [] },
        ],
    },
    "Biochemistry": {
        2026: [
            { category: 'major_specific', label: "BIOLOGY", validDepartments: ["BB"], excludedCourses: [] },
            { category: 'major_specific', label: "CHEMISTRY AND BIOCHEMISTRY", validDepartments: ["BB","CH"], excludedCourses: [] },
        ],
    },
    "Bioinformatics and Computational Biology": {
        2026: [
            { category: 'major_specific', label: "ADVANCED DISCIPLINARY COURSES", validDepartments: ["BB","CH","CS","MA"], excludedCourses: [] },
            { category: 'major_specific', label: "BIOLOGY", validDepartments: ["BB"], excludedCourses: [] },
            { category: 'major_specific', label: "CHEMISTRY", validDepartments: ["CH"], excludedCourses: [] },
            { category: 'major_specific', label: "COMPUTER SCIENCE", validDepartments: ["CS"], excludedCourses: [] },
            { category: 'major_specific', label: "MATHEMATICS", validDepartments: ["MA"], excludedCourses: [] },
        ],
        2029: [
            { category: 'major_specific', label: "BIOLOGY FOUNDATION", validDepartments: ["BB"], excludedCourses: [] },
            { category: 'major_specific', label: "CHEMISTRY FOUNDATION", validDepartments: ["CH"], excludedCourses: [] },
            { category: 'major_specific', label: "COMPUTER SCIENCE FOUNDATION", validDepartments: ["CS"], excludedCourses: [] },
            { category: 'major_specific', label: "MATHEMATICS FOUNDATION", validDepartments: ["MA"], excludedCourses: [] },
        ],
    },
    "Biology and Biotechnology": {
        2026: [
            { category: 'major_specific', label: "BIOLOGY AND BIOTECHNOLOGY", validDepartments: ["BB"], excludedCourses: ["BB 1000","BB 1001","BB 1002","BB 1003","BCB 1003"] },
            { category: 'major_specific', label: "CHEMISTRY", validDepartments: ["CH"], excludedCourses: [] },
            { category: 'major_specific', label: "MATHEMATICAL SCIENCES, PHYSICS, COMPUTER SCIENCE, ENGINEERING", validDepartments: ["CS","ES","MA","PH"], excludedCourses: [] },
            { category: 'major_specific', label: "RELATED COURSES", validDepartments: ["BB","BCB","CE","CH","CHE"], excludedCourses: [] },
        ],
        2028: [
            { category: 'major_specific', label: "BIOLOGY AND BIOTECHNOLOGY", validDepartments: ["BB"], excludedCourses: ["BB 1001","BB 1002","BB 1003","BB 1004","BCB 1003"] },
            { category: 'major_specific', label: "CHEMISTRY", validDepartments: ["CH"], excludedCourses: [] },
            { category: 'major_specific', label: "QUANTITATIVE REASONING", validDepartments: ["BCB","CS","DS","MA","PH"], excludedCourses: [] },
            { category: 'major_specific', label: "RELATED COURSES", validDepartments: ["BB","BCB","CE","CH","CHE"], excludedCourses: ["BB 4900"] },
        ],
        2030: [
            { category: 'major_specific', label: "BIOLOGY AND BIOTECHNOLOGY", validDepartments: ["BB"], excludedCourses: ["BB 1001","BB 1002","BB 1003","BB 1004","BCB 1003"] },
            { category: 'major_specific', label: "CHEMISTRY", validDepartments: ["CH"], excludedCourses: [] },
            { category: 'major_specific', label: "QUANTITATIVE REASONING", validDepartments: ["BCB","CS","DS","MA","PH"], excludedCourses: [] },
            { category: 'major_specific', label: "RELATED COURSES", validDepartments: ["BB","BCB","BME","CE","CH","CHE","MA"], excludedCourses: ["BB 4900"] },
        ],
    },
    "Biomedical Engineering": {
        2026: [
            { category: 'major_specific', label: "ENGINEERING", validDepartments: ["AE","AREN","BME","CE","CHE","ECE","ME","RBE"], excludedCourses: ["BME 1001","BME 1004","BME 3110","BME 532","BME 560","BME 562","BME 564","BME 593","CE 3022","RBE 3100"] },
            { category: 'major_specific', label: "SUPPLEMENTAL SCIENCE", validDepartments: ["BB","CH","CS","FY","MA","PH"], excludedCourses: [] },
            { category: 'social_science', label: "SOCIAL SCIENCE", validDepartments: ["ID"], excludedCourses: [] },
        ],
        2027: [
            { category: 'major_specific', label: "ENGINEERING", validDepartments: ["AE","AREN","BME","CE","CHE","ECE","ES","ME","RBE"], excludedCourses: ["BME 1001","BME 1004","BME 3110","BME 532","BME 560","BME 562","BME 564","BME 593","CE 3022","RBE 3100"] },
            { category: 'major_specific', label: "SUPPLEMENTAL SCIENCE", validDepartments: ["BB","CH","CS","FY","MA","PH"], excludedCourses: [] },
            { category: 'social_science', label: "SOCIAL SCIENCE", validDepartments: ["ID"], excludedCourses: [] },
        ],
        2028: [
            { category: 'major_specific', label: "ENGINEERING Distribution requirement", validDepartments: ["AE","AREN","BME","CE","CHE","ECE","ES","ME","RBE"], excludedCourses: ["BME 1001","BME 1004","BME 3110","BME 532","BME 560","BME 562","BME 564","BME 593","CE 3022","RBE 3100"] },
            { category: 'major_specific', label: "SUPPLEMENTAL SCIENCE", validDepartments: ["BB","CH","CS","FY","MA","PH"], excludedCourses: [] },
        ],
    },
    "Business": {
        2026: [
            { category: 'major_specific', label: "BASIC SCIENCE (2/3 units)", validDepartments: ["BB","CH","GE","PH"], excludedCourses: [] },
            { category: 'major_specific', label: "BREADTH ELECTIVES (3/3 units)", validDepartments: ["ACC","BB","BUS","CH","CS","DS","ECON","ENV","ETR","FIN","GE","GOV","MA","MIS","MKT","OBC","OIE","PH","PSY","SD","SOC","SS","STS"], excludedCourses: ["ID 2050","SS 2050"] },
            { category: 'major_specific', label: "COMPUTER SCIENCE (1/3 units)", validDepartments: ["CS"], excludedCourses: ["CS 2022","CS 3043"] },
            { category: 'major_specific', label: "MATHEMATICS (2/3 calculus + 2/3 statistics = 4/3 units)", validDepartments: ["MA"], excludedCourses: [] },
        ],
    },
    "Business Analytics and Applied AI": {
        2030: [
            { category: 'major_specific', label: "BASIC SCIENCE (2/3 units)", validDepartments: ["BB","CH","GE","PH"], excludedCourses: [] },
            { category: 'major_specific', label: "COMPUTER SCIENCE (1/3 units)", validDepartments: ["CS"], excludedCourses: ["CS 2022","CS 3043"] },
            { category: 'major_specific', label: "MATHEMATICS (5/3 units)", validDepartments: ["MA"], excludedCourses: [] },
        ],
    },
    "Chemical Engineering": {
        2026: [
            { category: 'major_specific', label: "ADVANCED CHEMISTRY AND NATURAL SCIENCE (5/3 unit)", validDepartments: ["BB","CH","GE","PH"], excludedCourses: [] },
            { category: 'major_specific', label: "ENGINEERING SCIENCE AND DESIGN (6 units)", validDepartments: ["BME","CE","CHE","ECE","FP","ME","MFE","MTE","RBE","SYS"], excludedCourses: [] },
        ],
    },
    "Chemistry": {
        2026: [
            { category: 'major_specific', label: "CHEMISTRY REQUIREMENT (12/3)", validDepartments: ["CH"], excludedCourses: [] },
            { category: 'major_specific', label: "MATHEMATICS AND PHYSICS REQUIREMENT (7/3 unit)", validDepartments: ["MA","PH"], excludedCourses: [] },
        ],
    },
    "Civil Engineering": {
        2026: [
            { category: 'major_specific', label: "ADDITIONAL MATHEMATICS AND BASIC SCIENCE (1/3 units)", validDepartments: ["BB","CH","FY","GE","MA","PH"], excludedCourses: [] },
            { category: 'major_specific', label: "BASIC SCIENCE (4/3 units)", validDepartments: ["BB","CH","GE","PH"], excludedCourses: [] },
            { category: 'major_specific', label: "CIVIL ENGINEERING - CORE (4/3 units)", validDepartments: ["CE"], excludedCourses: [] },
            { category: 'major_specific', label: "CIVIL ENGINEERING - DEPTH (3/3 units)", validDepartments: ["CE"], excludedCourses: [] },
            { category: 'major_specific', label: "CIVIL ENGINEERING LABORATORY EXPERIENCE (2/3 unit)", validDepartments: ["CE"], excludedCourses: [] },
            { category: 'major_specific', label: "FUNDAMENTAL ENGINEERING SCIENCE (6/3 units)", validDepartments: ["CE","ES"], excludedCourses: [] },
            { category: 'major_specific', label: "MATHEMATICS (7/3 units)", validDepartments: ["MA"], excludedCourses: [] },
        ],
    },
    "Computer Science": {
        2026: [
            { category: 'major_specific', label: "BASIC SCIENCE and/or ENGINEERING SCIENCE (5/3 units)", validDepartments: ["AE","BB","BME","CE","CH","CHE","ECE","ES","GE","ME","PH","RBE"], excludedCourses: [] },
            { category: 'major_specific', label: "COMPUTER SCIENCE (18/3 units)", validDepartments: ["CS"], excludedCourses: ["CS 2119"] },
            { category: 'major_specific', label: "MATHEMATICS (7/3 units)", validDepartments: ["MA"], excludedCourses: [] },
        ],
        2028: [
            { category: 'major_specific', label: "BASIC SCIENCE and/or ENGINEERING SCIENCE (5/3 units)", validDepartments: ["AE","BB","BME","CE","CH","CHE","ECE","ES","GE","ME","PH","RBE"], excludedCourses: ["BME 1004","RBE 3100"] },
            { category: 'major_specific', label: "COMPUTER SCIENCE (18/3 units)", validDepartments: ["CS"], excludedCourses: ["CS 2119"] },
            { category: 'major_specific', label: "MATHEMATICS (7/3 units)", validDepartments: ["MA"], excludedCourses: [] },
        ],
    },
    "Cybersecurity": {
        2030: [
            { category: 'major_specific', label: "ADDITIONAL BASIC AND/OR ENGINEERING SCIENCE (2/3 units)", validDepartments: ["BB","BME","CH","CHE","ES","GE","ME","PH","RBE"], excludedCourses: ["BME 1004","RBE 3100"] },
            { category: 'major_specific', label: "BASIC SCIENCE (3/3 units)", validDepartments: ["BB","CH","GE","PH"], excludedCourses: [] },
            { category: 'major_specific', label: "MATHEMATICS (6/3 units)", validDepartments: ["MA"], excludedCourses: [] },
        ],
    },
    "Data Science": {
        2026: [
            { category: 'major_specific', label: "COMPUTER SCIENCE (3/3 unit)", validDepartments: ["CS"], excludedCourses: [] },
            { category: 'major_specific', label: "MATHEMATICAL SCIENCES (5/3 unit)", validDepartments: ["MA"], excludedCourses: [] },
            { category: 'social_science', label: "SOCIAL SCIENCE (2/3 unit)", validDepartments: ["ECON","ENV","GOV","ID","PSY","SD","SOC","SS","STS"], excludedCourses: [] },
        ],
    },
    "Economic Science": {
        2026: [
            { category: 'major_specific', label: "ECONOMICS (3 units)", validDepartments: ["ECON"], excludedCourses: [] },
            { category: 'major_specific', label: "MATHEMATICS (2 units)", validDepartments: ["MA"], excludedCourses: [] },
            { category: 'social_science', label: "OTHER SOCIAL SCIENCE (1 unit)", validDepartments: ["ECON","ENV","GOV","ID","PSY","SD","SOC","STS"], excludedCourses: [] },
        ],
        2028: [
            { category: 'major_specific', label: "ECONOMICS", validDepartments: ["ECON"], excludedCourses: [] },
            { category: 'major_specific', label: "ECONOMICS AND/OR BUSINESS", validDepartments: ["BUS","ECON"], excludedCourses: [] },
            { category: 'social_science', label: "OTHER SOCIAL SCIENCE", validDepartments: ["ECON","ENV","GOV","ID","PSY","SD","SOC","STS"], excludedCourses: [] },
        ],
    },
    "Electrical and Computer Engineering": {
        2026: [
            { category: 'major_specific', label: "ADDITIONAL ENGINEERING SCIENCE AND DESIGN", validDepartments: ["AE","AREN","BME","CE","CHE","CS","ECE","ES","FP","ME","RBE"], excludedCourses: ["CS 2011","CS 2022","CS 3043"] },
            { category: 'major_specific', label: "CHEMISTRY or BIOLOGY", validDepartments: ["BB","CH"], excludedCourses: [] },
            { category: 'major_specific', label: "COMPUTER SCIENCE", validDepartments: ["CS","ECE"], excludedCourses: ["CS 2011","CS 2022","CS 3043"] },
            { category: 'major_specific', label: "ELECTRICAL AND COMPUTER ENGINEERING", validDepartments: ["ECE","ES"], excludedCourses: [] },
            { category: 'major_specific', label: "MATH or BASIC SCIENCE", validDepartments: ["BB","CH","GE","MA","PH"], excludedCourses: [] },
            { category: 'major_specific', label: "MATHEMATICS", validDepartments: ["MA"], excludedCourses: [] },
            { category: 'major_specific', label: "PHYSICS", validDepartments: ["PH"], excludedCourses: [] },
        ],
        2028: [
            { category: 'major_specific', label: "Additional ELECTRICAL AND COMPUTER ENGINEERING", validDepartments: ["ECE","ES"], excludedCourses: [] },
            { category: 'major_specific', label: "Additional ENGINEERING SCIENCE AND DESIGN", validDepartments: ["AE","AREN","BME","CE","CHE","CS","ECE","ES","FP","ME","RBE"], excludedCourses: ["CS 2011","CS 2022","CS 3043"] },
            { category: 'major_specific', label: "Additional MATH or BASIC SCIENCE", validDepartments: ["BB","CH","GE","MA","PH"], excludedCourses: [] },
            { category: 'major_specific', label: "CHEMISTRY or BIOLOGY", validDepartments: ["BB","CH"], excludedCourses: [] },
            { category: 'major_specific', label: "COMPUTATIONAL ENGINEERING", validDepartments: ["CS","ECE"], excludedCourses: ["CS 2011","CS 2022","CS 3043"] },
            { category: 'major_specific', label: "ELECTRICAL ENGINEERING", validDepartments: ["ECE","ES"], excludedCourses: [] },
            { category: 'major_specific', label: "MATHEMATICS", validDepartments: ["MA"], excludedCourses: [] },
            { category: 'major_specific', label: "PHYSICS", validDepartments: ["PH"], excludedCourses: [] },
        ],
    },
    "Environmental and Sustainability Studies": {
        2026: [
            { category: 'major_specific', label: "ENVIRONMENTAL SCIENCE AND ENGINEERING", validDepartments: ["BB","CE","CH","CHE","ES","GE","PH"], excludedCourses: [] },
            { category: 'major_specific', label: "ENVIRONMENTAL STUDIES CORE", validDepartments: ["ENV"], excludedCourses: [] },
        ],
        2029: [
            { category: 'major_specific', label: "ENVIRONMENTAL SCIENCE AND ENGINEERING", validDepartments: ["BB","BUS","CE","CH","CHE","CS","DS","ES","GE","ME","PH","RBE"], excludedCourses: [] },
            { category: 'major_specific', label: "ENVIRONMENTAL STUDIES CORE", validDepartments: ["ENV"], excludedCourses: [] },
        ],
    },
    "Environmental Engineering": {
        2026: [
            { category: 'major_specific', label: "BASIC SCIENCE", validDepartments: ["BB","CH","GE","PH"], excludedCourses: [] },
            { category: 'major_specific', label: "MATHEMATICS", validDepartments: ["MA"], excludedCourses: [] },
            { category: 'major_specific', label: "SUPPLEMENTAL SCIENCE", validDepartments: ["BB","CH"], excludedCourses: [] },
        ],
    },
    "Financial Technology": {
        2027: [
            { category: 'major_specific', label: "BASIC SCIENCE", validDepartments: ["BB","CH","GE","PH"], excludedCourses: [] },
            { category: 'major_specific', label: "COMPUTER SCIENCE", validDepartments: ["CS"], excludedCourses: ["CS 2022","CS 3043"] },
            { category: 'major_specific', label: "MATHEMATICS", validDepartments: ["MA"], excludedCourses: [] },
            { category: 'social_science', label: "SOCIAL SCIENCES", validDepartments: ["ECON"], excludedCourses: [] },
        ],
    },
    "Humanities and Arts": {
        2026: [
            { category: 'major_specific', label: "HUMANITIES AND ARTS (6 units)", validDepartments: ["AB","AR","CN","EN","GN","HI","HU","INTL","MU","PY","RE","RH","SP","TH","WR"], excludedCourses: [] },
        ],
        2029: [
            { category: 'major_specific', label: "HUMANITIES AND ARTS (6 units) (Notes 1, 2)", validDepartments: ["AB","AR","CN","EN","GN","HI","HU","INTL","ISE","MU","PY","RE","SP","TH","WR"], excludedCourses: [] },
        ],
    },
    "Industrial Engineering": {
        2026: [
            { category: 'major_specific', label: "TECHNICAL ELECTIVES (3/3 units)", validDepartments: ["CE","CHE","CS","ECE","ES","ME","OIE","RBE"], excludedCourses: ["CE 3022","CS 1004","CS 1101","CS 1102","CS 3043","ES 1000","ES 3323"] },
        ],
    },
    "Information Systems and Technology": {
        2028: [
            { category: 'major_specific', label: "BASIC SCIENCE (2/3 units)", validDepartments: ["BB","CH","GE","PH"], excludedCourses: [] },
            { category: 'major_specific', label: "COMPUTER SCIENCE (1/3 units)", validDepartments: ["CS"], excludedCourses: ["CS 2022","CS 3043"] },
        ],
    },
    "International and Global Studies": {
        2026: [
            { category: 'major_specific', label: "INTERNATIONAL & GLOBAL CORE (1 unit) (Note 1)", validDepartments: ["INTL"], excludedCourses: [] },
        ],
    },
    "Management Engineering": {
        2026: [
            { category: 'major_specific', label: "BASIC SCIENCE (2/3 units)", validDepartments: ["BB","CH","GE","PH"], excludedCourses: [] },
            { category: 'major_specific', label: "COMPUTER SCIENCE (1/3 units)", validDepartments: ["CS"], excludedCourses: ["CS 2022","CS 3043"] },
            { category: 'major_specific', label: "MGE MAJOR w/ BME CONCENTRATION (6/3 units)", validDepartments: ["BB","BME"], excludedCourses: [] },
            { category: 'major_specific', label: "TECHNICAL COURSES (3/3 units)", validDepartments: ["AE","BB","BME","CE","CH","CHE","CS","DS","ECE","ES","GE","IE","MA","ME","PH","RBE"], excludedCourses: ["CE 3022","CS 3043","ES 1000","RBE 3100"] },
            { category: 'social_science', label: "SOCIAL SCIENCES (2/3 units)", validDepartments: ["DEV","ECON","ENV","GOV","PSY","SD","SOC","SS","STS"], excludedCourses: [] },
        ],
        2027: [
            { category: 'major_specific', label: "BASIC SCIENCE (2/3 units)", validDepartments: ["BB","CH","GE","PH"], excludedCourses: [] },
            { category: 'major_specific', label: "COMPUTER SCIENCE (1/3 units)", validDepartments: ["CS"], excludedCourses: ["CS 2022","CS 3043"] },
            { category: 'major_specific', label: "MGE MAJOR w/ BME CONCENTRATION (6/3 units)", validDepartments: ["BB","BME"], excludedCourses: [] },
            { category: 'major_specific', label: "TECHNICAL COURSES (3/3 units)", validDepartments: ["AE","BB","BME","CE","CH","CHE","CS","DS","ECE","ES","GE","IE","MA","ME","PH","RBE"], excludedCourses: ["CE 3022","CS 3043","ES 1000","RBE 3100"] },
        ],
        2028: [
            { category: 'major_specific', label: "BASIC SCIENCE (2/3 units)", validDepartments: ["BB","CH","GE","PH"], excludedCourses: [] },
            { category: 'major_specific', label: "COMPUTER SCIENCE (1/3 units)", validDepartments: ["CS"], excludedCourses: ["CS 2022","CS 3043"] },
            { category: 'major_specific', label: "MGE MAJOR w/ BME CONCENTRATION (6/3 units)", validDepartments: ["BB","BME"], excludedCourses: [] },
            { category: 'major_specific', label: "TECHNICAL COURSES (3/3 units)", validDepartments: ["AE","BB","BME","CE","CH","CHE","CS","DS","ECE","ES","GE","MA","ME","OIE","PH","RBE"], excludedCourses: ["CE 3022","CS 3043","ES 1000","RBE 3100"] },
        ],
    },
    "Management Information Systems": {
        2027: [
            { category: 'free_electives', label: "FREE ELECTIVES (5/3 units)", validDepartments: [], excludedCourses: ["CS 2022","CS 3043"] },
            { category: 'major_specific', label: "BASIC SCIENCE (2/3 units)", validDepartments: ["BB","CH","GE","PH"], excludedCourses: [] },
            { category: 'major_specific', label: "BREADTH ELECTIVES (3/3 units)", validDepartments: ["ACC","BUS","ETR","FIN","MIS","MKT","OBC","OIE"], excludedCourses: [] },
            { category: 'major_specific', label: "MATHEMATICS (2/3 calculus + 2/3 statistics = 4/3 units)", validDepartments: ["ACC","BB","BUS","CH","CS","DS","ECON","ENV","ETR","FIN","GE","GOV","MA","MIS","MKT","OBC","OIE","PH","PSY","SD","SOC","SS","STS"], excludedCourses: ["ID 2050","SS 2050"] },
        ],
    },
    "Marketing Analytics": {
        2030: [
            { category: 'free_electives', label: "FREE ELECTIVES (3/3 units)", validDepartments: [], excludedCourses: ["CS 2022","CS 3043"] },
            { category: 'major_specific', label: "BASIC SCIENCE (2/3 units)", validDepartments: ["BB","CH","GE","PH"], excludedCourses: [] },
        ],
    },
    "Mathematical Sciences": {
        2026: [
            { category: 'major_specific', label: "MATHEMATICAL PROGRAM - RELATED COURSES (2 units)", validDepartments: ["BB","CH","CS","DS","ES","GE","PH"], excludedCourses: ["FIN 1250"] },
        ],
        2027: [
            { category: 'major_specific', label: "MATHEMATICAL PROGRAM - RELATED COURSES (2 units)", validDepartments: ["BB","CH","CS","DS","ES","GE","PH"], excludedCourses: ["FIN 1250"] },
            { category: 'social_science', label: "SOCIAL SCIENCE (2/3 units)", validDepartments: ["ECON","ENV","GOV","ID","PSY","SD","SOC","SS","STS"], excludedCourses: [] },
        ],
    },
    "Mechanical Engineering": {
        2026: [
            { category: 'major_specific', label: "SCIENCE (3/3 unit)", validDepartments: ["CH","PH"], excludedCourses: [] },
            { category: 'major_specific', label: "STUDENT SELECTED COURSES (2/3 unit)", validDepartments: ["BB","CH","GE","MA","PH"], excludedCourses: [] },
        ],
    },
    "Physics": {
        2026: [
            { category: 'major_specific', label: "PHYSICS (5 units, includes MQP)", validDepartments: ["CH","ES","PH"], excludedCourses: [] },
        ],
    },
    "Physics Applied": {
        2027: [
            { category: 'major_specific', label: "PHYSICS (5 units, includes MQP)", validDepartments: ["CH","ES","PH"], excludedCourses: [] },
        ],
    },
    "Policy Studies": {
        2028: [
            { category: 'major_specific', label: "BASIC SCIENCE", validDepartments: ["BB","CH","DS","GE","PH"], excludedCourses: [] },
            { category: 'major_specific', label: "CORE GOVERNMENT COURSES", validDepartments: ["GOV"], excludedCourses: [] },
            { category: 'major_specific', label: "ECONOMICS", validDepartments: ["ECON"], excludedCourses: [] },
            { category: 'major_specific', label: "GOVERNMENT ELECTIVE COURSES", validDepartments: ["GOV"], excludedCourses: [] },
            { category: 'major_specific', label: "MATHEMATICS", validDepartments: ["MA"], excludedCourses: [] },
        ],
    },
    "Professional Writing": {
        2026: [
            { category: 'major_specific', label: "WRITING AND RHETORIC CONCENTRATION", validDepartments: ["WR"], excludedCourses: [] },
        ],
        2030: [
            { category: 'major_specific', label: "Communication Electives", validDepartments: [], excludedCourses: ["ID 2050"] },
            { category: 'major_specific', label: "Writing and Rhetoric Core", validDepartments: ["WR"], excludedCourses: [] },
        ],
    },
    "Psychological Science": {
        2026: [
            { category: 'major_specific', label: "BASIC SCIENCE, COMPUTER SCIENCE, AND/OR ENGINEERING", validDepartments: [], excludedCourses: ["CS 2022","CS 3043"] },
            { category: 'major_specific', label: "MATHEMATICS", validDepartments: ["MA"], excludedCourses: [] },
            { category: 'major_specific', label: "PSYCHOLOGICAL SCIENCE", validDepartments: ["PSY"], excludedCourses: [] },
            { category: 'major_specific', label: "PSYCHOLOGICAL SCIENCE AND/OR RELATED COURSES", validDepartments: ["AB","AR","BB","BME","BUS","CH","CS","DEV","ECON","EN","ENV","GN","GOV","HI","HU","ID","IMGD","INTL","MA","ME","MKT","MU","OBC","PY","RBE","RE","SD","SOC","SP","WR"], excludedCourses: [] },
        ],
        2028: [
            { category: 'major_specific', label: "BASIC SCIENCE, COMPUTER SCIENCE, AND/OR ENGINEERING", validDepartments: [], excludedCourses: ["CS 2022","CS 3043"] },
            { category: 'major_specific', label: "MATHEMATICS", validDepartments: ["MA"], excludedCourses: [] },
            { category: 'major_specific', label: "PSYCHOLOGICAL SCIENCE", validDepartments: ["PSY"], excludedCourses: [] },
            { category: 'major_specific', label: "PSYCHOLOGICAL SCIENCE AND/OR RELATED COURSES", validDepartments: ["BB","BME","BUS","CH","CS","DEV","ECON","EN","ENV","GOV","HI","HU","ID","IMGD","INTL","MA","ME","MKT","OBC","PY","RBE","RE","SD","SOC","SP","WR"], excludedCourses: [] },
        ],
    },
    "Robotics Engineering": {
        2026: [
            { category: 'major_specific', label: "COMPUTER SCIENCE", validDepartments: ["CS"], excludedCourses: [] },
            { category: 'major_specific', label: "ELECTRICAL AND COMPUTER ENGINEERING", validDepartments: ["ECE"], excludedCourses: [] },
            { category: 'major_specific', label: "ENGINEERING SCIENCE", validDepartments: ["ES"], excludedCourses: [] },
            { category: 'major_specific', label: "ENTREPRENEURSHIP", validDepartments: ["ETR"], excludedCourses: [] },
            { category: 'major_specific', label: "MATHEMATICS", validDepartments: ["MA"], excludedCourses: [] },
            { category: 'major_specific', label: "OTHER SCIENCE", validDepartments: ["BB","CH","GE","PH"], excludedCourses: [] },
            { category: 'major_specific', label: "PHYSICS", validDepartments: ["PH"], excludedCourses: [] },
            { category: 'major_specific', label: "ROBOTICS ENGINEERING", validDepartments: ["RBE"], excludedCourses: ["RBE 3100"] },
        ],
        2030: [
            { category: 'major_specific', label: "COMPUTER SCIENCE", validDepartments: ["CS"], excludedCourses: [] },
            { category: 'major_specific', label: "ELECTRICAL AND COMPUTER ENGINEERING", validDepartments: ["ECE"], excludedCourses: [] },
            { category: 'major_specific', label: "ENGINEERING SCIENCE", validDepartments: ["ES"], excludedCourses: [] },
            { category: 'major_specific', label: "ENTREPRENEURSHIP", validDepartments: ["ETR"], excludedCourses: [] },
            { category: 'major_specific', label: "MATHEMATICS", validDepartments: ["MA"], excludedCourses: [] },
            { category: 'major_specific', label: "OTHER SCIENCE", validDepartments: ["BB","CH","GE","PH"], excludedCourses: [] },
            { category: 'major_specific', label: "PHYSICS", validDepartments: ["PH"], excludedCourses: [] },
            { category: 'major_specific', label: "ROBOTICS ENGINEERING", validDepartments: ["RBE"], excludedCourses: ["RBE 2020","RBE 300X","RBE 3100"] },
        ],
    },
    "Society Technology Policy": {
        2026: [
            { category: 'major_specific', label: "MATHEMATICS", validDepartments: ["MA"], excludedCourses: [] },
            { category: 'major_specific', label: "STP CORE COURSES", validDepartments: ["GOV"], excludedCourses: [] },
            { category: 'major_specific', label: "STP GENERAL COURSES", validDepartments: ["GOV"], excludedCourses: [] },
        ],
    },
};
