/**
 * Generates src/utils/iconPaths.ts from SVG files in src/assets/icons/
 *
 * Run: bun run generate-icons
 */

import { readdirSync, readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const ICONS_DIR = join(__dirname, "../src/assets/icons");
const OUTPUT_FILE = join(__dirname, "../src/utils/iconPaths.ts");

function kebabToUpperSnake(filename: string): string {
  return filename
    .replace(".svg", "")
    .split("-")
    .map((part) => part.toUpperCase())
    .join("_");
}

function kebabToCamel(filename: string): string {
  const parts = filename.replace(".svg", "").split("-");
  return parts
    .map((part, i) => i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1))
    .join("") + "Icon";
}

function generateIconPaths(): void {
  const svgFiles = readdirSync(ICONS_DIR)
    .filter((file) => file.endsWith(".svg"))
    .sort();

  if (svgFiles.length === 0) {
    console.error("No SVG files found in", ICONS_DIR);
    process.exit(1);
  }

  console.log(`Found ${svgFiles.length} SVG files`);

  const icons = svgFiles.map((filename) => {
    const constantName = kebabToUpperSnake(filename);
    const variableName = kebabToCamel(filename);
    const svgContent = readFileSync(join(ICONS_DIR, filename), "utf-8")
      .trim()
      .replace(/\s+class="[^"]*"/g, "") // Remove class attributes from source SVG
      .replace(/stroke="#000000"/g, 'stroke="currentColor"') // Replace black stroke with currentColor
      .replace(/fill="#000000"/g, 'fill="currentColor"'); // Replace black fill with currentColor

    return {
      filename,
      constantName,
      variableName,
      svgContent,
    };
  });

  const imports = icons
    .map((icon) => `import ${icon.variableName} from '../assets/icons/${icon.filename}?url';`)
    .join("\n");

  const iconNames = icons.map((icon) => `  | '${icon.constantName}'`).join("\n");

  const iconsObject = icons
    .map((icon) => `  ${icon.constantName}: ${icon.variableName},`)
    .join("\n");

  const inlineSvgsObject = icons
    .map((icon) => `  ${icon.constantName}: \`${icon.svgContent}\`,`)
    .join("\n");

  const output = `/**
 * Centralized icon path constants for type-safe asset references.
 * Icons are imported from src/assets/icons/ and Vite handles base path resolution.
 *
 * Exports both URL paths (for img tags) and inline SVG content (for better CSS styling).
 *
 * AUTO-GENERATED by scripts/generate-icon-paths.ts
 * Run: bun run generate-icons
 */

import { logger } from './logger';

${imports}

export type IconName =
${iconNames};

/** Icon URL paths for SVG assets, with Vite base path resolution (use in img tags). */
export const ICONS: Record<IconName, string> = {
${iconsObject}
} as const;

/** Inline SVG markup using currentColor, so icons can be styled via CSS fill/stroke. */
export const INLINE_SVGS: Record<IconName, string> = {
${inlineSvgsObject}
} as const;

function sanitizeClassName(className: string): string {
  return className.replace(/[^a-zA-Z0-9_\\-\\s]/g, '');
}

// Output is fully determined by (iconName, className), so memoize it: callers
// render the same icons via {@html} on every component re-render (e.g. CourseList
// runs this ~6x per row x 100 rows), and each call otherwise re-does a string
// .replace(). The set of (icon, class) pairs is small and fixed, so the cache is
// bounded. Only successful resolutions are cached - the missing-icon path stays
// uncached so its logger.warn keeps surfacing the bug.
const inlineSVGCache = new Map<string, string>();

/** Returns inline SVG markup for an icon, optionally with custom CSS classes. */
export function getInlineSVG(iconName: IconName, className?: string): string {
  const cacheKey = \`\${iconName}|\${className ?? ''}\`;
  const cached = inlineSVGCache.get(cacheKey);
  if (cached !== undefined) return cached;

  const svg = INLINE_SVGS[iconName];

  if (!svg) {
    logger.warn(\`Icon "\${iconName}" not found, using fallback\`);
    const fallback = '<svg viewBox="0 0 24 24" width="16" height="16"><circle cx="12" cy="12" r="10" fill="currentColor"/></svg>';
    return className ? fallback.replace('<svg', \`<svg class="\${sanitizeClassName(className)}"\`) : fallback;
  }

  const result = className
    ? svg.replace('<svg', \`<svg class="\${sanitizeClassName(className)}"\`)
    : svg;
  inlineSVGCache.set(cacheKey, result);
  return result;
}
`;

  writeFileSync(OUTPUT_FILE, output, "utf-8");
  console.log(`Generated ${OUTPUT_FILE}`);
  console.log(`  Icons: ${icons.map((i) => i.constantName).join(", ")}`);
}

try {
  generateIconPaths();
} catch (error) {
  console.error("Error generating icon paths:", error);
  process.exit(1);
}
