name: Update Course Data

on:
  schedule:
    - cron: '*/15 * * * *' # Every 15 minutes
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Fetch latest course data
        run: |
          mkdir -p public
          node scripts/fetch-course-data.js
      
      - name: Run course data converter
        run: |
          cd WorkdayToPlannerConverter-master
          java -cp "lib/json-simple-1.1.1.jar:src" jsonToXml.Converter
      
      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet public/course-data.json public/course-data-constructed.json; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push if changed
        if: steps.changes.outputs.changed == 'true'
        run: |
          # Create timestamp file with current UTC time
          echo "{\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%S.000Z)\",\"utc\":\"$(date -u +%Y-%m-%d\ %H:%M\ UTC)\"}" > public/last-updated.json
          
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/course-data.json public/course-data-constructed.json public/last-updated.json
          git commit -m "Update course data $(date -u +%Y-%m-%d\ %H:%M\ UTC)"
          git push